// <auto-generated />
using System;
using Itau.CompraProgramada.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Itau.CompraProgramada.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260301213220_AddDataSaidaToCliente")]
    partial class AddDataSaidaToCliente
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Itau.CompraProgramada.Domain.Entities.CestaRecomendacao", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<bool>("Ativa")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("DataDesativacao")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("CestasRecomendacao");
                });

            modelBuilder.Entity("Itau.CompraProgramada.Domain.Entities.Cliente", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Cpf")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime>("DataAdesao")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("DataSaida")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<decimal>("ValorMensal")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("Cpf")
                        .IsUnique();

                    b.ToTable("Clientes");
                });

            modelBuilder.Entity("Itau.CompraProgramada.Domain.Entities.ContaGrafica", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<long?>("ClienteId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("NumeroConta")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<int>("Tipo")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId")
                        .IsUnique();

                    b.HasIndex("NumeroConta")
                        .IsUnique();

                    b.ToTable("ContasGraficas");
                });

            modelBuilder.Entity("Itau.CompraProgramada.Domain.Entities.Custodia", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("ContaGraficaId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("DataUltimaAtualizacao")
                        .HasColumnType("datetime(6)");

                    b.Property<decimal>("PrecoMedio")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<int>("Quantidade")
                        .HasColumnType("int");

                    b.Property<string>("Ticker")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("ContaGraficaId");

                    b.ToTable("Custodias");
                });

            modelBuilder.Entity("Itau.CompraProgramada.Domain.Entities.Distribuicao", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("CustodiaFilhoteId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("DataDistribuicao")
                        .HasColumnType("datetime(6)");

                    b.Property<long>("OrdemCompraId")
                        .HasColumnType("bigint");

                    b.Property<decimal>("PrecoUnitario")
                        .HasPrecision(18, 5)
                        .HasColumnType("decimal(18,5)");

                    b.Property<int>("Quantidade")
                        .HasColumnType("int");

                    b.Property<string>("Ticker")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("CustodiaFilhoteId");

                    b.HasIndex("OrdemCompraId");

                    b.ToTable("Distribuicoes");
                });

            modelBuilder.Entity("Itau.CompraProgramada.Domain.Entities.EventoIR", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("ClienteId")
                        .HasColumnType("bigint");

                    b.Property<string>("Cpf")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("DataEvento")
                        .HasColumnType("datetime(6)");

                    b.Property<decimal>("PrecoUnitario")
                        .HasColumnType("decimal(65,30)");

                    b.Property<bool>("PublicadoKafka")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("Quantidade")
                        .HasColumnType("int");

                    b.Property<string>("Ticker")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Tipo")
                        .HasColumnType("int");

                    b.Property<decimal>("ValorBase")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ValorIR")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("EventosIR");
                });

            modelBuilder.Entity("Itau.CompraProgramada.Domain.Entities.HistoricoValorMensal", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("ClienteId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("DataAlteracao")
                        .HasColumnType("datetime(6)");

                    b.Property<decimal>("ValorAnterior")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal>("ValorNovo")
                        .HasColumnType("decimal(65,30)");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId");

                    b.ToTable("HistoricoValoresMensais");
                });

            modelBuilder.Entity("Itau.CompraProgramada.Domain.Entities.ItemCesta", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("CestaId")
                        .HasColumnType("bigint");

                    b.Property<long?>("CestaRecomendacaoId")
                        .HasColumnType("bigint");

                    b.Property<decimal>("Percentual")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<string>("Ticker")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("CestaRecomendacaoId");

                    b.ToTable("ItensCesta");
                });

            modelBuilder.Entity("Itau.CompraProgramada.Domain.Entities.OrdemCompra", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("ContaMasterId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("DataExecucao")
                        .HasColumnType("datetime(6)");

                    b.Property<decimal>("PrecoUnitario")
                        .HasPrecision(18, 5)
                        .HasColumnType("decimal(18,5)");

                    b.Property<int>("Quantidade")
                        .HasColumnType("int");

                    b.Property<string>("Ticker")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("TipoMercado")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("OrdensCompra");
                });

            modelBuilder.Entity("Itau.CompraProgramada.Domain.Entities.Rebalanceamento", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("ClienteId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("DataRebalanceamento")
                        .HasColumnType("datetime(6)");

                    b.Property<decimal>("LucroLiquido")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("PrecoMedio")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<int>("Quantidade")
                        .HasColumnType("int");

                    b.Property<string>("TickerComprado")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("TickerVendido")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Tipo")
                        .HasColumnType("int");

                    b.Property<decimal>("ValorVenda")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Rebalanceamentos");
                });

            modelBuilder.Entity("Itau.CompraProgramada.Domain.Entities.ContaGrafica", b =>
                {
                    b.HasOne("Itau.CompraProgramada.Domain.Entities.Cliente", null)
                        .WithOne("ContaGrafica")
                        .HasForeignKey("Itau.CompraProgramada.Domain.Entities.ContaGrafica", "ClienteId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Itau.CompraProgramada.Domain.Entities.Custodia", b =>
                {
                    b.HasOne("Itau.CompraProgramada.Domain.Entities.ContaGrafica", null)
                        .WithMany("Custodias")
                        .HasForeignKey("ContaGraficaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Itau.CompraProgramada.Domain.Entities.Distribuicao", b =>
                {
                    b.HasOne("Itau.CompraProgramada.Domain.Entities.Cliente", null)
                        .WithMany()
                        .HasForeignKey("CustodiaFilhoteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Itau.CompraProgramada.Domain.Entities.OrdemCompra", "OrdemCompra")
                        .WithMany("Distribuicoes")
                        .HasForeignKey("OrdemCompraId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("OrdemCompra");
                });

            modelBuilder.Entity("Itau.CompraProgramada.Domain.Entities.HistoricoValorMensal", b =>
                {
                    b.HasOne("Itau.CompraProgramada.Domain.Entities.Cliente", null)
                        .WithMany("HistoricoValores")
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Itau.CompraProgramada.Domain.Entities.ItemCesta", b =>
                {
                    b.HasOne("Itau.CompraProgramada.Domain.Entities.CestaRecomendacao", null)
                        .WithMany("Itens")
                        .HasForeignKey("CestaRecomendacaoId");
                });

            modelBuilder.Entity("Itau.CompraProgramada.Domain.Entities.CestaRecomendacao", b =>
                {
                    b.Navigation("Itens");
                });

            modelBuilder.Entity("Itau.CompraProgramada.Domain.Entities.Cliente", b =>
                {
                    b.Navigation("ContaGrafica")
                        .IsRequired();

                    b.Navigation("HistoricoValores");
                });

            modelBuilder.Entity("Itau.CompraProgramada.Domain.Entities.ContaGrafica", b =>
                {
                    b.Navigation("Custodias");
                });

            modelBuilder.Entity("Itau.CompraProgramada.Domain.Entities.OrdemCompra", b =>
                {
                    b.Navigation("Distribuicoes");
                });
#pragma warning restore 612, 618
        }
    }
}
